import React from "react";
import UpdatesCard from "./UpdatesCard";

const data = [
  {
    date: "9th january 2024",
    title: "Dota 2 Update - 1/8/2024",
    description: `Some items from the Frostivus 2023 Treasure Chest were missing unusual variants. Those have been added. Over the next couple days, unusual items from these sets that should have been dropped will be granted.`,
    summary:
      "In addition, over the last few days we've addressed several gameplay issues:",
    updates: [
      "Fixed Frostivus wards not being selectable/attackable",
      "Fixed an issue where pinging certain items in quickbuy could cause the game to lag for teammates",
      "Fixed an issue where Arc Warden Tempest Doubles could gain gold by selling Midas",
      "Fixed Doom Devour Neutral abilities not leveling up automatically at the time when neutral abilities would scale",
      "Fixed Lina permanently gaining Fiery Soul stacks until she casts another spells if she was broken when supercharging with Laguna Blade",
      "Fixed Tiny Tree particle showing at the wrong time",
      "Fixed a rare server crash with motion controlled abilities (e.g. Spirit Breaker Charge of Darkness)",
      "Fixed an issue with Profile Showcase where items could appear floating before the rest of the hero loaded and fixed an issue with anchor points on ultrawide monitors",
      "Added missing descriptions for various recipes",
      "Fixed some bugs in the tutorials in the Learn tab caused by the 7.35 Gameplay Patch",
    ],
  },
  {
    date: "21 DEC 2023",
    title: "7.35b Gameplay Patch",
    description: "Patch 7.35b is out now. You can check the notes here.",
    summary:
      "Over the last few days, we've also addressed several gameplay issues:",
    updates: [
      "Fixed tabbing through selections being in creation order, rather than reverse creation order",
      "Fixed the combat log not displaying instances of damage that occurred on the same frame from the same source to the same target",
      "Fixed Block of Cheese not entering cooldown when receiving damage",
      "Fixed Parasma going on cooldown when denying",
      "Fixed Granite Golem's Granite Aura not correctly adjusting health when removed",
      "Fixed Batrider's Sticky Napalm applying damage from Mage Slayer",
      "Fixed Centaur Warrunner keeping the Work Horse ability after selling Aghanim's Scepter",
      "Fixed Centaur Warrunner's Hitch A Ride ability being in the wrong slot if applying Aghanim's Blessing",
      "Fixed Medusa having any damage shield making Dagger items unmuteable",
      "Fixed Meepo's Earthbind talent not giving the intended 2.5s cooldown reduction",
      "Fixed Meepo leveling Divided We Stand on a clone not giving Meepo the correct stats",
      "Fixed Muerta's Dead Shot interrupting some movement abilities on units that are debuff immune",
      "Fixed enemies being able to see Slardar's Bash of the Deep modifier stack count changing when he's hidden in the Fog of War",
      "Fixed Storm Spirit's Attack Range when Overloaded talent not working correctly with Aghanim's Shard",
      "Fixed Vengeful Spirit's Nether Swap barrier not being refreshable",
      "Fixed Viper's break particles being shown incorrectly",
      "Fixed Wraith King's Skeletons following invisible units",
      "Fixed inconsistencies in Spell Amplification/Damage tooltips",
    ],
  },
  {
    date: "19 DEC 2023",
    title: "Dota 2 Update - 12/18/2023",
    summary: "Over the last few days we've addressed several gameplay issues:",
    updates: [
      "Fixed Bloodstone Area of Effect bonus still active on passive abilities if it was dropped or sold",
      "Fixed Bloodthorn mana regen being 3.0 instead of 3.5 from the sum of its components",
      "Fixed Butterfly not counting hero's base attack speed for its bonuses",
      "Fixed Cleave not working on magical attacks (i.e. Revenant's Brooch)",
      "Fixed a rare server crash when toggling Doubloon",
      "Fixed Khanda not doing lethal damage correctly",
      "Fixed Khanda and Phylactery not sharing cooldowns",
      "Fixed Tree Throw, Toss, Snowball, Soul Assumption and Sticky Bomb not triggering Phylactery/Khanda",
      "Fixed incorrect interaction between Phylactery/Khanda and Spectre's Spectral Dagger",
      "Fixed Phylactery/Khanda working on illusions",
      "Fixed Meteor Hammer incorrectly giving more Agility than Intelligence",
      "Fixed Parasma not granting 1.5 mana regen from its components",
      "Fixed Revenant's Brooch incorrectly giving true strike",
      "Fixed a server crash caused by interaction between Abaddon's Aphotic Shield expiring, Safety Bubble, and Blade Mail",
      "Fixed Arc Warden's Tempest Double not cloning Royal Jelly",
      "Fixed Dawnbreaker's Starbreaker sometimes not going in the targeted direction",
      "Fixed non-ranged units getting true strike benefits of Drow Ranger's Glacier",
      "Fixed some cases where Drow Ranger could get stuck trying to leave her Glacier",
      "Fixed Chen's Penitence granting bonus attack range to Chen's melee creeps",
      "Fixed Chen's Divine Favor regeneration not applying to Chen's creeps",
      "Fixed Chen's level 10 talent Divine Favor Teleport Delay not applying correctly",
      "Fixed Invoker not being able to pick up Lotuses from the Lotus Pools",
      "Fixed Juggernaut's Blade Fury attack rate not updating if Juggernaut's attack speed changes.",
      "Fixed Juggernaut's Omnislash/Swiftslash not damaging ethereal units even with Revenant's Brooch",
      "Fixed Juggernaut's Blade Fury incorrect interaction with Harpoon",
      "Fixed Lich's Chain Frost not being affected by AoE increase",
      "Fixed items in the Bear's stash becoming lost when Lone Druid upgrades the Bear",
      "Fixed Omniknight's Guardian Angel charges not updating properly upon acquiring and dropping Aghanim's Scepter",
      "Fixed Pangolier's Shield Crash damage type not being correctly changed to Physical damage",
      "Fixed a rare serve crash with Pudge's Dismember",
      "Fixed Silencer's Last Word dealing less damage to creeps than intended",
      "Fixed Black Dragon's Splash Attack not working correctly",
      "Fixed a few server crashes",
      "Fixed various tooltip issues",
      "Re-added Hero Names as an option for heroes on the minimap",
      "Fixed minimap settings preview not scaling the arrow when scaling the icon",
      "Fixed a bug where previewing Persona items would sometimes show them on the base model (or vice versa) in Armory / Loadout",
    ],
  },
  {
    date: "15 DEC 2023",
    title: "Dota 2 Update - 12/14/2023",
    summary:
      "We've fixed a number of issues since the initial Frostivus release:",
    updates: [
      "Fixed an issue with client-side display of Royal Jelly's buff stats",
      "Fixed Safety Bubble having its shield reset to full when dropped and re-equipped",
      "Fixed Unwavering Condition not working properly",
      "Fixed some testing items being purchasable in-game",
      "Added Roshan's Banner to the Glossary",
      "Fixed King Kringle's Skeletons not having the correct hats!",
      "Fixed King Kringle's Skeletons' hoods and portraits",
      "Fixed King Kringle's Skeletons not showing as Frostivus-appropriate in some locales",
      "Fixed the particles for Roshan's Banner sometimes not being properly removed",
      "Improved the look of the Tower Range indicator based on player use and made the danger threshold vary based on player hero level",
      "Fixed various small issues with the 7.35 patch notes",
      "Fixed an issue with the Vampiric Spirit spell icon for King Kringle",
      "Fixed Jingle Fist Immortal display on the treasure screen",
      "Fixed an issue with movie previews while the Frostivus carousel was cycling during the treasure opening animation",
    ],
    clarification: "For clarity, Frostivus Gift contents vary per account:",
    gifts: [
      "For accounts shared with other users or services: a game ban",
      "For alt accounts used for smurfing: a game ban",
      "For main accounts associated with a banned smurf account: a piece of coal",
      "For all other accounts: free cosmetic items, with higher behavior score accounts receiving higher-tier items",
    ],
  },
  {
    date: "13 OCT 2023",
    title: "Dota 2 Update - 10/12/2023",
    summary:
      "We've fixed a number of issues leading up and during the first day of Group Stage:",
    updates: [
      "Fixed Earth Spirit being stuck in Rolling Boulder if Centaur Warrunner casts Work Horse while Earth Spirit is transforming",
      "Fixed a bad interaction between Kunkka X Marks the Spot and Impale",
      "Fixed some cases where players were unable to watch matches via DotaTV",
      "Fixed cases where in-game predictions weren't working",
      "Fixed Bingo square progress not being visible on client",
      "Fixed visual artifacts on some talent photos and stickers",
      "Fixed an issue where Roshan could go walkabout again",
      "Fixed Centaur Hoof Stomp wind-up being dispellable",
      "Fixed Invoker not restoring his own mana from EMP",
      "Fixed an issue where Kunkka X Marks the Spot could fail to return a unit with very high Status Resistance",
      "Fixed Lone Druid Spirit Bear receiving experience when using Midas",
      "Fixed Marci Sidekick not displaying correctly on the client",
      "Fixed a server crash when using Muerta Parting Shot on a hero that is leashed to Lone Druid Spirit Bear with Grimstroke Soulbind",
      "Fixed Techies Mines triggering for but not damaging flying units",
      "Added a filter option for saved sets in the Armory",
      "Fixed two rare client crashes with dropped items",
      "Fixed retrieval of neutral items from stash sometimes returning another player's item",
      "Changed a number of settings including 'Use Extra Large Minimap', 'Quick Attack', etc. to be saved in Steam Cloud",
      "Fixed being unable to assign neutral slot and TP quickcast when using Advanced Quickcast Hotkeys",
      "Fixed 'Dynamically Scale Hero Icons' option causing icons to flicker in size",
      "Fixed an issue where hero icons on the minimap could jitter",
      "Fixed various Predictions and Fantasy issues",
    ],
  },
  {
    date: "9 SEP 2023",
    title: "7.34c Gameplay Patch",
    summary:
      "Patch 7.34c is out now. You can check the notes here.\nOracle saw too far into the future. That is now fixed.",
    updates: [
      "Fixed an issue where using Armlet could lead to double death bounties",
      "Fixed Soul Ring not removing temporary mana at the end of its buff duration",
      "Fixed enemy flagbearer creeps sometimes not showing their banners",
      "Fixed shield rune not being visible on enemy units until they attack or get attacked",
      "Fixed Ion Shell sometimes not being visible",
      "Fixed Terrorblade illusions appearing the same as the real Terrorblade",
      "Fixed buffs like Haste, God's Strength, and Fire Remnant not showing on the status bar of heroes",
      "Fixed backdoor protection not being shown as a buff on towers nor the shield icon next to their health",
      "Fixed the invisibility effect not showing on enemy heroes under a friendly Sentry Ward",
      "Fixed Haste rune not showing as a buff on the status bar or being shown visually on the hero",
      "Fixed Pudge Rot being invisible",
      "Fixed an issue where Rubick stole Death Pact for free when stealing Skeleton Walk from Clinkz",
      "Fixed Lone Druid's Spirit Bear counting towards Monkey King's Jinggu Mastery stacks",
      "Fixed Lone Druid's Spirit Bear death counting towards permanent stacks for Axe, Necrophos, Slark, Lion, and Tidehunter",
      "Fixed Desolator gaining damage when killing Spirit Bear",
      "Fixed Spirit Bear attacks counting as Hero attacks when attacking Clinkz Skeletons, Lich Ice Spire, Phoenix Supernova, Pugna Nether Ward, Tidehunter Dead in the Water anchor, Undying Tombstone, Zeus Nimbus.",
      "Fixed Spirit Bear death refreshing Axe Culling Blade and lowering Windranger Focus Fire cooldown with Level 25 talent",
      "Fixed Lone Druid Spirit Bear displayed as the unit name on the Minimap",
      "Fixed Tormentor not granting Spirit Bear a Shard if Lone Druid already has one, and not allowing allies to get Tormentor gold bounty if all allies already have the Shard",
      "Fixed Tormentor particles sometimes showing in fog of war",
      "Fixed a bug where inventory item icons would sometimes disappear when dragging them",
      "Fixed a number of items' ability effects failing to equip in the Armory/Loadout",
      "Fixed some free event reward items not showing up in the Armory",
      "Fixed an issue saving the Taunt slot on custom sets",
      "Fixed the default global light and shadow colors on the Autumn terrain",
      "Fixed a display-only bug where certain magic resistance and physical resistance percentage values were being incorrectly rounded down a point below their actual values",
      "Fixed a display-only bug where units with zero health or mana regeneration values would display as negative zero due to network-encoding quantization effects",
      "Fixed a crash in Workshop Tools",
    ],
  },
  {
    date: "2 SEP 2023",
    title: "Dota 2 Update - 9/1/2023",
    summary:
      "Since releasing The Summer Client Update we've addressed a number of issues:",
    updates: [
      "Fixed a bug that would appear to allow you to commend/dislike the same player multiple times in postgame",
      "Fixed an issue that would sometimes cause behavior score or communication score to get set to 0 incorrectly (the affected accounts have had their appropriate scores restored)",
      "Re-added the ability to rotate your hero with mousewheel in the Armory and pregame",
      "Re-added the ability to demo custom terrains",
      "In games where the majority of connected players have a behavior score too low to allow them to pause the game, those players will now be able to unpause if the game has been paused for at least 5s",
      "Added persona selector to pregame loadout",
      "Added slot headings to pregame loadout",
      "Re-introduced Hero Relics into the shard shop",
      "Disabled rebundling for items with unlocked styles, or which unpack with dynamic gems",
      "Owned world items can now be demoed through the item details popup",
      "Improved the display of chat wheels in the new Armory",
      "Commending a player no longer prints a chat message every time (to prevent post-game commend sprees from pushing all actual chat offscreen)",
      "Added a new, distinct sound for disliking a player",
      "Fixed grouping by item type in the All Items tab in the Armory",
      "Fixed announcer packs not loading properly when entering pregame",
      "Fixed places in the new Armory where fonts would sometimes display at an incorrect size",
      "Fixed an issue that would sometimes cause dead units to not stay dead (Undying, Spirit Bear, Wraith King)",
      "Fixed multikill banners not being accessible in the new Armory",
      "Fixed an issue that would cause the game to change monitors when running in fullscreen on multi-monitor displays",
      "Fixed Dark Seer's 'More Than Mental Mass' taunt not playing sounds",
      "Fixed Phoenix's Crimson Dawn set only changing the appearance of the head instead of the full set",
      "Fixed server crashes involving abilities from Dark Seer, Razor, and Hoodwink",
      "Fixed a client crash when displaying certain tooltips (including Tranquil Boots)",
      "Fixed custom game JavaScript support",
      "Fixed Hammer crashing on startup",
      "Fixed a crash when returning to the dashboard after playing a game",
      "Fixed some over-bright rendering in Vulkan when color-correction post-processing was enabled",
      "Fixed a crash in the Vulkan renderer on Linux",
      "Fixed a crash on Linux GPUs with low memory",
      "Fixed fullscreen flickering on multi-monitor Linux systems",
      "Fixed a crash on MacOS versions older than 10.15",
      "Fixed a hang on MacOS when purchasing certain items in the Armory",
      "Fixed a particle crash on older Windows machines without SSE4.1 support",
      "Fixed terrain sometimes displaying incorrectly (or being invisible) on low-spec Windows machines",
      "Fixed a particle rendering error with Phoenix's Solar Gyre",
      "Fixed display of owned Kill Streak Effect in the Shard Shop",
      "Fixed incorrect items sometimes appearing under the Tools section in the Shard Shop",
      "Fixed some cosmetic particle effects not showing properly when previewing items in the Loadout or in the Armory (Void Spirit weapon particles, for example)",
      "Fixed summons appearing next to heroes in postgame",
      "Fixed Dota Plus quest to commend players not correctly counting all commends",
      "Fixed a server crash when players were spectating under certain conditions",
      "Fixed a rare courier-related server crash in Turbo",
      "Fixed an issue where using Armlet could cause a unit to behave oddly on death (for example, give death bounty twice, or in Wraith King's case, be teleported to the fountain on Reincarnation)",
    ],
  },
  {
    date: "15 AUG 2023",
    title: "7.34b Gameplay Patch",
    summary: "Patch 7.34b is out now. You can check the notes here.",
    updates: [
      "Fixed Arc Warden Magnetic Field granting bonus damage instead of base damage",
      "Fixed Bane illusion waking up Nightmared Units",
      "Fixed Brewmaster Level 25 Talent Drunken Brawler Passive on brewlings Primal Companions not getting extra bonuses from getting Cinder Brew on them",
      "Fixed Brewmaster Level 10 Talent not applying the attack damage to Scepter Primal Companions",
      "Fixed Crystal Maiden Crystal Clone not mentioning projectile disjointing on cast in tooltip",
      "Fixed Ember Spirit Flame Guard not updating the first time magic damage was applied",
      "Fixed 'Pierces Debuff Immunity' tooltip for Grimstroke Soulbind",
      "Fixed tooltip description for Keeper of the Light's Chakra Magic",
      "Fixed a server crash with Lone Druid and Spirit Bear",
      "Fixed Break disabling Phantom Assassin Phantom Strike's lifesteal",
      "Fixed Phantom Assassin Blur dispellable by Lotus Pools and Twin gates",
      "Fixed showing a HUD error for Templar Assassin shown while pressing Ctrl",
      "Fixed 'Dispellable' tooltip for Terrorblade Demon Zeal",
      "Fixed Witch Doctor Death Ward unable to target creep-heroes",
      "Fixed Enchantress Little Friends being only partially undispellable",
    ],
  },
  {
    date: "12 AUG 2023",
    title: "Dota 2 Update - 8/11/2023",
    summary: "",
    updates: [
      "Fixed Captain's Mode pick order display",
      "Fixed some regressions of 7.33e changes",
      "Removed references in the Glossary to Outposts granting XP",
      "Fixed the locations mentioned in Outpost Captured messages",
      "Fixed and clarified various tooltips",
      "Fixed Alchemist not being able to grant Aghanim's Scepter to Lone Druid's Spirit Bear",
      "Fixed an issue where Elder Titan Astral Spirit would keep flying without stopping when casting Echo Stomp",
      "Fixed Lifestealer level 25 talent not granting bonus damage",
      "Fixed Lone Druid's Spirit Bear not respecting auto-attack settings",
      "Fixed Lone Druid's Spirit Bear not being able to be switched to with Tab",
      "Fixed Lone Druid's Spirit Bear not gaining strength from Power Treads",
      "Fixed Lone Druid's Spirit Bear illusions not gaining bonus attack damage from Lone Druid's level",
      "Fixed Lone Druid's Spirit Bear Fetch piercing Debuff Immunity when it should not be able to",
      "Fixed Lone Druid Spirit Link mistakenly healing the Spirit Bear",
      "Fixed Phantom Assassin level 25 talent +7% Coup de Grace Crit Chance not working",
      "Fixed Timbersaw level 15 Whirling Death Stat Loss talent having no effect on universal heroes",
      "Fixed the initial attack from Witch Doctor Death Ward not piercing debuff immunity",
      "Fixed Zeus shard toggle state being reset on death (but still showing as toggled on)",
    ],
  },
];

const Main = () => {
  return (
    <div className="bg-patchesPage min-h-[100vh]">
      {data.map((data) => (
        <UpdatesCard key={data.date} {...data} />
      ))}
    </div>
  );
};

export default Main;
